pipeline {
  agent any

  stages {
    stage('Build ') {
      steps {
        //Compile java code
        sh 'javac helloworld.java'
      }
    }
    stage('Run') {
      steps {
        //Run java program
        sh 'helloworld'
      }
    }
  }
}
